// Auto-generated mqjs_stdlib.h header
// This file is generated by gen_mqjs_headers.py

#ifndef MQJS_STDLIB_H
#define MQJS_STDLIB_H


// Minimal standard library for Bruce JavaScript interpreter
const char *mqjs_stdlib = " \
    // Global Bruce Utility functions \
    bruce.log = function(...args) { bruce.println(...args); }; \
";

#endif // MQJS_STDLIB_H
